name: car
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  uninstall_apps: ^0.0.4
  flutter_appavailability: ^0.0.21
  splashscreen: ^1.2.0
  flutter_svg: ^0.17.4
  share: ^0.6.4+3
  url_launcher: ^5.4.11
  device_apps: ^1.0.9
  fluttertoast: ^4.0.1
  intent: ^1.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/